### ISSUE TITLE
Add content to landing/splash page

### ISSUE THREAD

**Issue by bouzidanas** [bezda-team/rhp-documentation#7]
# Overview

The landing page still mostly contains the original placeholder content. This needs to be replaced with content related to **rhp**.

# Todo

- [x] Change title to `react html plots`
- [x] Update tagline
- [x] Add splash page graphic
- [ ] Change blocks into navigation cards that navigate to **rhp** resources like community, blog, docs, gallery, etc
- [ ] add footer content
